---
server:
  port: 9000


spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URL}
          searchPaths: ${APP_NAME}

logging:
  level:
    org:
      springframework: debug
