---
server:
  port: ${TOMCAT_PORT}

spring:
  cloud:
    config:
      server:
        git:
#          uri: ${GIT_URL}
          uri: file://${CONFIG_REPO}/
          searchPaths: ${APP_NAME}

logging:
  level:
    org:
      springframework: debug
